spring:
  datasource:
    url: jdbc:postgresql://db:5432/cinema_service
    username: my_service
    password: my_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: movie-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"


management:
  endpoints:
    web:
      exposure:
        include: '*'
#          - health
#          - info
#          - prometheus
#          - metrics
  metrics:
    enable:
      prometheus: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
#      percentile-histograms:
#        "http.server.requests": true
    tags:
      application: cinema-service
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs.yaml
  swagger-ui:
    path: /swagger-ui.html
    enabled: true